import type { SupabaseBike } from "../../types/garage";
import { demoBikeImages } from "./images";

export const demoGarageBikes: SupabaseBike[] = [
  {
    id: "bmw-r1300gs-2026",
    make: "BMW",
    model: "R1300GS",
    variant: null,
    year: 2026,
    category: "Adventure",
    engine_cc: 1300,
    image: demoBikeImages.bmwR1300GS.path,
    heroImageUrl: demoBikeImages.bmwR1300GS.path,
    sourceLabel: "BMW Motorrad official model page",
    sourceUrl: "https://www.bmwmotorcycles.com/en/models/adventure/r1300gs.html",
  },
  {
    id: "bmw-r1300gsa-2025",
    make: "BMW",
    model: "R1300GSA",
    variant: null,
    year: 2025,
    category: "Adventure",
    engine_cc: 1300,
    image: demoBikeImages.bmwR1300GSA.path,
    heroImageUrl: demoBikeImages.bmwR1300GSA.path,
    sourceLabel: "BMW Motorrad official model page",
    sourceUrl:
      "https://www.bmwmotorcycles.com/en/models/adventure/r1300gs-adventure.html",
  },
  {
    id: "bmw-r1300gsa-triple-black-2025",
    make: "BMW",
    model: "R1300GSA",
    variant: "Triple Black",
    year: 2025,
    category: "Adventure",
    engine_cc: 1300,
    image: demoBikeImages.bmwR1300GSA.path,
    heroImageUrl: demoBikeImages.bmwR1300GSA.path,
    sourceLabel: "BMW Motorrad official model page",
    sourceUrl:
      "https://www.bmwmotorcycles.com/en/models/adventure/r1300gs-adventure.html",
  },
  {
    id: "bmw-r1300gsa-2026",
    make: "BMW",
    model: "R1300GSA",
    variant: "Adventure",
    year: 2026,
    category: "Adventure",
    engine_cc: 1300,
    image: demoBikeImages.bmwR1300GSA.path,
    heroImageUrl: demoBikeImages.bmwR1300GSA.path,
    sourceLabel: "BMW Motorrad official model page",
    sourceUrl:
      "https://www.bmwmotorcycles.com/en/models/adventure/r1300gs-adventure.html",
  },
  {
    id: "yamaha-tenere-700-2026",
    make: "Yamaha",
    model: "Tenere 700",
    variant: null,
    year: 2026,
    category: "Adventure",
    engine_cc: 689,
    image: demoBikeImages.yamahaTenere700.path,
    heroImageUrl: demoBikeImages.yamahaTenere700.path,
    sourceLabel: "Yamaha official model page",
    sourceUrl: "https://www.yamahamotorsports.com/models/tenere-700/features",
  },
  {
    id: "ktm-890-adventure-2025",
    make: "KTM",
    model: "890 Adventure",
    variant: null,
    year: 2025,
    category: "Adventure",
    engine_cc: 889,
    image: demoBikeImages.ktm890Adventure.path,
    heroImageUrl: demoBikeImages.ktm890Adventure.path,
    sourceLabel: "KTM official model page",
    sourceUrl:
      "https://www.ktm.com/en-us/models/travel/2025-ktm-890-adventure-r.html",
  },
  {
    id: "suzuki-v-strom-800de-2023",
    make: "Suzuki",
    model: "V-Strom 800DE",
    variant: null,
    year: 2023,
    category: "Adventure",
    engine_cc: 776,
    image: demoBikeImages.suzukiVStrom800DE.path,
    heroImageUrl: demoBikeImages.suzukiVStrom800DE.path,
    sourceLabel: "Temporary Outback Motortek YouTube thumbnail",
    sourceUrl: "https://www.youtube.com/watch?v=felXZX8_8Wo",
  },
];
