import type { Product } from "../../types/garage";
import { demoAccessoryImages } from "./images";

const bmwR1300GSAFamily = [
  "bmw-r1300gsa-2025",
  "bmw-r1300gsa-triple-black-2025",
  "bmw-r1300gsa-2026",
];
const bmwR1300GSFamily = ["bmw-r1300gs-2026", ...bmwR1300GSAFamily];
const yamahaTenereFamily = ["yamaha-tenere-700-2026"];

export const demoGarageProducts: Product[] = [
  {
    id: 7001,
    name: "Zega Mundo Pannier System",
    brand: "Touratech",
    price: 0,
    supplierUrl: "https://touratech-usa.com/store/Zega-Mundo-Pannier-System-BMW%20R1300GS",
    subcategory: "Hard panniers",
    affiliateLinks: [
      {
        vendorName: "Touratech USA",
        url: "https://touratech-usa.com/store/Zega-Mundo-Pannier-System-BMW%20R1300GS",
        label: "View at Touratech",
        priority: 1,
      },
    ],
    fallbackUrl: "https://touratech-usa.com/store/Zega-Mundo-Pannier-System-BMW%20R1300GS",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "luggage",
    description:
      "Aluminium pannier system curated for BMW R 1300 GS touring and expedition setups.",
    image: demoAccessoryImages.panniers.path,
    imageSourceLabel: demoAccessoryImages.panniers.sourceLabel,
    sourceLabel: "Touratech official product page",
    sourceUrl: "https://touratech-usa.com/store/Zega-Mundo-Pannier-System-BMW%20R1300GS",
    fitmentConfidence: "Exact fit",
    featuredOrder: 1,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7002,
    name: "Pannier Racks",
    brand: "Touratech",
    price: 0,
    supplierUrl: "https://touratech-usa.com/store/Touratech-Pannier-Racks-BMW-R1300GS",
    subcategory: "Rack systems",
    affiliateLinks: [
      {
        vendorName: "Touratech USA",
        url: "https://touratech-usa.com/store/Touratech-Pannier-Racks-BMW-R1300GS",
        label: "View at Touratech",
        priority: 1,
      },
    ],
    fallbackUrl: "https://touratech-usa.com/store/Touratech-Pannier-Racks-BMW-R1300GS",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "luggage",
    description: "Dedicated pannier rack platform for BMW R 1300 GS luggage systems.",
    image: demoAccessoryImages.panniers.path,
    imageSourceLabel: demoAccessoryImages.panniers.sourceLabel,
    sourceLabel: "Touratech official product page",
    sourceUrl: "https://touratech-usa.com/store/Touratech-Pannier-Racks-BMW-R1300GS",
    fitmentConfidence: "Exact fit",
    featuredOrder: 2,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7003,
    name: "Zega Topcase Rack",
    brand: "Touratech",
    price: 0,
    supplierUrl: "https://touratech-usa.com/store/Zega-Topcase-Rack-BMW-R1300GS",
    subcategory: "Top-box mounts",
    affiliateLinks: [
      {
        vendorName: "Touratech USA",
        url: "https://touratech-usa.com/store/Zega-Topcase-Rack-BMW-R1300GS",
        label: "View at Touratech",
        priority: 1,
      },
    ],
    fallbackUrl: "https://touratech-usa.com/store/Zega-Topcase-Rack-BMW-R1300GS",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "luggage",
    description: "Rear rack and top-case mount for load-carrying R 1300 GS builds.",
    image: demoAccessoryImages.topBox.path,
    imageSourceLabel: demoAccessoryImages.topBox.sourceLabel,
    sourceLabel: "Touratech official product page",
    sourceUrl: "https://touratech-usa.com/store/Zega-Topcase-Rack-BMW-R1300GS",
    fitmentConfidence: "Exact fit",
    featuredOrder: 3,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7004,
    name: "NOMAX Tank Bag V3.0",
    brand: "Mosko Moto",
    price: 0,
    supplierUrl: "https://moskomoto.com/products/nomax-tank-bag-v3-0",
    subcategory: "Tank bags",
    affiliateLinks: [
      {
        vendorName: "Mosko Moto",
        url: "https://moskomoto.com/products/nomax-tank-bag-v3-0",
        label: "View at Mosko Moto",
        priority: 1,
      },
    ],
    fallbackUrl: "https://moskomoto.com/products/nomax-tank-bag-v3-0",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "luggage",
    description: "Premium adventure tank bag suited to long-distance BMW and Tenere cockpit setups.",
    image: demoAccessoryImages.tankBag.path,
    imageSourceLabel: demoAccessoryImages.tankBag.sourceLabel,
    sourceLabel: "Mosko Moto official product page",
    sourceUrl: "https://moskomoto.com/products/nomax-tank-bag-v3-0",
    fitmentConfidence: "Universal fit",
    featuredOrder: 4,
    compatibility: {
      bikeIds: [...bmwR1300GSFamily, ...yamahaTenereFamily, "ktm-890-adventure-2025"],
      universal: true,
    },
  },
  {
    id: 7005,
    name: "Upper Crash Bars",
    brand: "Outback Motortek",
    price: 0,
    supplierUrl: "https://outbackmotortek.com/product/bmw-r1300gs-upper-crash-bars/",
    subcategory: "Crash protection",
    affiliateLinks: [
      {
        vendorName: "Outback Motortek",
        url: "https://outbackmotortek.com/product/bmw-r1300gs-upper-crash-bars/",
        label: "View at Outback Motortek",
        priority: 1,
      },
    ],
    fallbackUrl: "https://outbackmotortek.com/product/bmw-r1300gs-upper-crash-bars/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "protection",
    description: "Upper crash-bar coverage for BMW R 1300 GS and GS Adventure bodywork.",
    image: demoAccessoryImages.crashBars.path,
    imageSourceLabel: demoAccessoryImages.crashBars.sourceLabel,
    sourceLabel: "Outback Motortek official product page",
    sourceUrl: "https://outbackmotortek.com/product/bmw-r1300gs-upper-crash-bars/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 5,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7006,
    name: "Skid Plate",
    brand: "Outback Motortek",
    price: 0,
    supplierUrl: "https://outbackmotortek.com/product/bmw-r-1300-gs-skid-plate/",
    subcategory: "Skid plates",
    affiliateLinks: [
      {
        vendorName: "Outback Motortek",
        url: "https://outbackmotortek.com/product/bmw-r-1300-gs-skid-plate/",
        label: "View at Outback Motortek",
        priority: 1,
      },
    ],
    fallbackUrl: "https://outbackmotortek.com/product/bmw-r-1300-gs-skid-plate/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "protection",
    description: "Heavy underbody protection for BMW R 1300 GS and GS Adventure travel builds.",
    image: demoAccessoryImages.skidPlate.path,
    imageSourceLabel: demoAccessoryImages.skidPlate.sourceLabel,
    sourceLabel: "Outback Motortek official product page",
    sourceUrl: "https://outbackmotortek.com/product/bmw-r-1300-gs-skid-plate/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 6,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7007,
    name: "Upper Crash Bar",
    brand: "SW-MOTECH",
    price: 0,
    supplierUrl: "https://sw-motech.us/en-us/p/4052572017807",
    subcategory: "Crash protection",
    affiliateLinks: [
      {
        vendorName: "SW-MOTECH",
        url: "https://sw-motech.us/en-us/p/4052572017807",
        label: "View at SW-MOTECH",
        priority: 1,
      },
    ],
    fallbackUrl: "https://sw-motech.us/en-us/p/4052572017807",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "protection",
    description: "Alternative upper-bar protection option for BMW R 1300 GS builds.",
    image: demoAccessoryImages.crashBars.path,
    imageSourceLabel: demoAccessoryImages.crashBars.sourceLabel,
    sourceLabel: "SW-MOTECH official product page",
    sourceUrl: "https://sw-motech.us/en-us/p/4052572017807",
    fitmentConfidence: "Exact fit",
    featuredOrder: 7,
    compatibility: {
      bikeIds: ["bmw-r1300gs-2026"],
    },
  },
  {
    id: 7008,
    name: "D7 PRO Multi-Beam Driving Light Pods",
    brand: "DENALI",
    price: 0,
    supplierUrl:
      "https://eu.denalielectronics.com/products/d7-pro-multi-beam-driving-light-pods-with-modular-x-lens-system",
    subcategory: "Auxiliary lights",
    affiliateLinks: [
      {
        vendorName: "DENALI",
        url: "https://eu.denalielectronics.com/products/d7-pro-multi-beam-driving-light-pods-with-modular-x-lens-system",
        label: "View at DENALI",
        priority: 1,
      },
    ],
    fallbackUrl:
      "https://eu.denalielectronics.com/products/d7-pro-multi-beam-driving-light-pods-with-modular-x-lens-system",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "lighting",
    description: "High-output auxiliary lighting for long-distance and poor-visibility riding.",
    image: demoAccessoryImages.ledLights.path,
    imageSourceLabel: demoAccessoryImages.ledLights.sourceLabel,
    sourceLabel: "DENALI official product page",
    sourceUrl:
      "https://eu.denalielectronics.com/products/d7-pro-multi-beam-driving-light-pods-with-modular-x-lens-system",
    fitmentConfidence: "Universal fit",
    featuredOrder: 8,
    compatibility: {
      bikeIds: [...bmwR1300GSFamily, ...yamahaTenereFamily, "ktm-890-adventure-2025"],
      universal: true,
    },
  },
  {
    id: 7009,
    name: "Upper Driving Light Mount",
    brand: "DENALI",
    price: 0,
    supplierUrl: "https://denalielectronics.com/products/upper-driving-light-mount-bmw-r1300gs-adventure",
    subcategory: "Lighting mounts",
    affiliateLinks: [
      {
        vendorName: "DENALI",
        url: "https://denalielectronics.com/products/upper-driving-light-mount-bmw-r1300gs-adventure",
        label: "View at DENALI",
        priority: 1,
      },
    ],
    fallbackUrl: "https://denalielectronics.com/products/upper-driving-light-mount-bmw-r1300gs-adventure",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "lighting",
    description: "Model-specific upper light mount for BMW R 1300 GS Adventure auxiliary lights.",
    image: demoAccessoryImages.ledLights.path,
    imageSourceLabel: demoAccessoryImages.ledLights.sourceLabel,
    sourceLabel: "DENALI official product page",
    sourceUrl: "https://denalielectronics.com/products/upper-driving-light-mount-bmw-r1300gs-adventure",
    fitmentConfidence: "Exact fit",
    featuredOrder: 9,
    compatibility: {
      bikeIds: bmwR1300GSAFamily,
    },
  },
  {
    id: 7010,
    name: "zumo XT2",
    brand: "Garmin",
    price: 0,
    supplierUrl: "https://www.garmin.com/en-US/p/1222490",
    subcategory: "GPS navigators",
    affiliateLinks: [
      {
        vendorName: "Garmin",
        url: "https://www.garmin.com/en-US/p/1222490",
        label: "View at Garmin",
        priority: 1,
      },
    ],
    fallbackUrl: "https://support.garmin.com/en-US/?faq=yJkoqbG9bz4A3pltfbxSv6",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "navigation",
    description: "Dedicated motorcycle GPS navigator often used in BMW and adventure-bike cockpit setups.",
    image: demoAccessoryImages.gpsMount.path,
    imageSourceLabel: demoAccessoryImages.gpsMount.sourceLabel,
    sourceLabel: "Garmin official product page",
    sourceUrl: "https://www.garmin.com/en-US/p/1222490",
    fitmentConfidence: "Universal fit",
    featuredOrder: 10,
    compatibility: {
      bikeIds: [...bmwR1300GSFamily, ...yamahaTenereFamily, "ktm-890-adventure-2025"],
      universal: true,
    },
  },
  {
    id: 7011,
    name: "GPS Mounting Bracket, Above Gauges",
    brand: "Touratech",
    price: 0,
    supplierUrl: "https://touratech-usa.com/Store/Touratech-GPS-Mounting-Bracket-Above-Gauges-BMW-R1300-GS",
    subcategory: "Navigation mounts",
    affiliateLinks: [
      {
        vendorName: "Touratech USA",
        url: "https://touratech-usa.com/Store/Touratech-GPS-Mounting-Bracket-Above-Gauges-BMW-R1300-GS",
        label: "View at Touratech",
        priority: 1,
      },
    ],
    fallbackUrl: "https://touratech-usa.com/Store/Touratech-GPS-Mounting-Bracket-Above-Gauges-BMW-R1300-GS",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "navigation",
    description: "Above-dash GPS mount for BMW R 1300 GS cockpit visibility and cleaner navigation placement.",
    image: demoAccessoryImages.gpsMount.path,
    imageSourceLabel: demoAccessoryImages.gpsMount.sourceLabel,
    sourceLabel: "Touratech official product page",
    sourceUrl: "https://touratech-usa.com/Store/Touratech-GPS-Mounting-Bracket-Above-Gauges-BMW-R1300-GS",
    fitmentConfidence: "Exact fit",
    featuredOrder: 11,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7012,
    name: "2\" Pivoting Bar Risers for 1 1/8\" Handlebar",
    brand: "ROX Speed FX",
    price: 0,
    supplierUrl: "https://roxspeedfx.com/products/2-pivoting-bar-risers-for-1-1-8-handlebar",
    subcategory: "Bar risers",
    affiliateLinks: [
      {
        vendorName: "ROX Speed FX",
        url: "https://roxspeedfx.com/products/2-pivoting-bar-risers-for-1-1-8-handlebar",
        label: "View at ROX Speed FX",
        priority: 1,
      },
    ],
    fallbackUrl: "https://roxspeedfx.com/products/2-pivoting-bar-risers-for-1-1-8-handlebar",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "ergonomics",
    description: "Pivoting risers that suit standing comfort and cockpit reach on ADV bikes.",
    image: demoAccessoryImages.risers.path,
    imageSourceLabel: demoAccessoryImages.risers.sourceLabel,
    sourceLabel: "ROX Speed FX official product page",
    sourceUrl: "https://roxspeedfx.com/products/2-pivoting-bar-risers-for-1-1-8-handlebar",
    fitmentConfidence: "Universal fit",
    featuredOrder: 12,
    compatibility: {
      bikeIds: [...bmwR1300GSFamily, ...yamahaTenereFamily, "ktm-890-adventure-2025"],
      universal: true,
    },
  },
  {
    id: 7013,
    name: "SoundBomb Mini Electromagnetic Low Tone Horn",
    brand: "DENALI",
    price: 0,
    supplierUrl: "https://denalielectronics.com/products/tt-sb-10200-b",
    subcategory: "Visibility and safety",
    affiliateLinks: [
      {
        vendorName: "DENALI",
        url: "https://denalielectronics.com/products/tt-sb-10200-b",
        label: "View at DENALI",
        priority: 1,
      },
    ],
    fallbackUrl: "https://denalielectronics.com/products/tt-sb-10200-b",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "safety-visibility",
    description: "Compact horn upgrade that improves conspicuity on road-biased and mixed ADV builds.",
    image: demoAccessoryImages.usbHub.path,
    imageSourceLabel: demoAccessoryImages.usbHub.sourceLabel,
    sourceLabel: "DENALI official product page",
    sourceUrl: "https://denalielectronics.com/products/tt-sb-10200-b",
    fitmentConfidence: "Universal fit",
    featuredOrder: 13,
    compatibility: {
      bikeIds: [...bmwR1300GSFamily, ...yamahaTenereFamily, "ktm-890-adventure-2025"],
      universal: true,
    },
  },
  {
    id: 7014,
    name: "Crash Bars Combo",
    brand: "Outback Motortek",
    price: 0,
    supplierUrl: "https://outbackmotortek.com/product/yamaha-tenere-700-crash-bars/",
    subcategory: "Crash protection",
    affiliateLinks: [
      {
        vendorName: "Outback Motortek",
        url: "https://outbackmotortek.com/product/yamaha-tenere-700-crash-bars/",
        label: "View at Outback Motortek",
        priority: 1,
      },
    ],
    fallbackUrl: "https://outbackmotortek.com/product/yamaha-tenere-700-crash-bars/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "protection",
    description: "Crash-bar setup for Yamaha Tenere 700 builds aimed at mixed and off-road use.",
    image: demoAccessoryImages.crashBars.path,
    imageSourceLabel: demoAccessoryImages.crashBars.sourceLabel,
    sourceLabel: "Outback Motortek official product page",
    sourceUrl: "https://outbackmotortek.com/product/yamaha-tenere-700-crash-bars/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 14,
    compatibility: {
      bikeIds: yamahaTenereFamily,
    },
  },
  {
    id: 7015,
    name: "Skid Plate",
    brand: "Outback Motortek",
    price: 0,
    supplierUrl: "https://outbackmotortek.com/product/yamaha-tenere-700-skid-plate/",
    subcategory: "Skid plates",
    affiliateLinks: [
      {
        vendorName: "Outback Motortek",
        url: "https://outbackmotortek.com/product/yamaha-tenere-700-skid-plate/",
        label: "View at Outback Motortek",
        priority: 1,
      },
    ],
    fallbackUrl: "https://outbackmotortek.com/product/yamaha-tenere-700-skid-plate/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "protection",
    description: "Under-engine protection for Yamaha Tenere 700 travel and trail builds.",
    image: demoAccessoryImages.skidPlate.path,
    imageSourceLabel: demoAccessoryImages.skidPlate.sourceLabel,
    sourceLabel: "Outback Motortek official product page",
    sourceUrl: "https://outbackmotortek.com/product/yamaha-tenere-700-skid-plate/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 15,
    compatibility: {
      bikeIds: yamahaTenereFamily,
    },
  },
  {
    id: 7016,
    name: "Clear Headlight Guard",
    brand: "Touratech",
    price: 0,
    supplierUrl: "https://www.touratech-usa.com/Store/Touratech-Clear-Headlight-Guard-1300-GS",
    subcategory: "Headlight protection",
    affiliateLinks: [
      {
        vendorName: "Touratech USA",
        url: "https://www.touratech-usa.com/Store/Touratech-Clear-Headlight-Guard-1300-GS",
        label: "View at Touratech",
        priority: 1,
      },
    ],
    fallbackUrl: "https://www.touratech-usa.com/Store/Touratech-Clear-Headlight-Guard-1300-GS",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "protection",
    description: "Clear headlight protection for BMW R 1300 GS front-end durability.",
    image: demoAccessoryImages.crashBars.path,
    imageSourceLabel: demoAccessoryImages.crashBars.sourceLabel,
    sourceLabel: "Touratech official product page",
    sourceUrl: "https://www.touratech-usa.com/Store/Touratech-Clear-Headlight-Guard-1300-GS",
    fitmentConfidence: "Exact fit",
    featuredOrder: 16,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7017,
    name: "HEX ezCAN",
    brand: "HEX",
    price: 0,
    supplierUrl: "https://abikething.com/product/hex-ezcan-ii-for-bmw-r1300-gs/",
    subcategory: "Accessory controllers",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/hex-ezcan-ii-for-bmw-r1300-gs/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/hex-ezcan-ii-for-bmw-r1300-gs/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "electrical",
    description:
      "CAN-bus accessory controller for integrating lights, horn, and add-on electronics on the BMW R1300GS and GSA platform.",
    image: demoAccessoryImages.usbHub.path,
    imageSourceLabel: demoAccessoryImages.usbHub.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/hex-ezcan-ii-for-bmw-r1300-gs/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 17,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7018,
    name: "Chigee Play for BMW",
    brand: "Chigee",
    price: 0,
    supplierUrl: "https://abikething.com/product/chigee-aio-5-play-for-bmw-smart-riding-display/",
    subcategory: "Connected displays",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/chigee-aio-5-play-for-bmw-smart-riding-display/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/chigee-aio-5-play-for-bmw-smart-riding-display/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "connectivity-navigation",
    description:
      "BMW-focused smart display for navigation, phone integration, and touring cockpit control.",
    image: demoAccessoryImages.gpsMount.path,
    imageSourceLabel: demoAccessoryImages.gpsMount.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/chigee-aio-5-play-for-bmw-smart-riding-display/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 18,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7019,
    name: "TR100",
    brand: "Chigee",
    price: 0,
    supplierUrl: "https://abikething.com/product/chigee-two-way-quick-charger/",
    subcategory: "Charging systems",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/chigee-two-way-quick-charger/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/chigee-two-way-quick-charger/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "electrical",
    description:
      "Portable two-way quick charger used here as part of a cleaner power and charging setup for tech-heavy touring.",
    image: demoAccessoryImages.usbHub.path,
    imageSourceLabel: demoAccessoryImages.usbHub.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/chigee-two-way-quick-charger/",
    fitmentConfidence: "Universal fit",
    featuredOrder: 19,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
      universal: true,
    },
  },
  {
    id: 7020,
    name: "Innovv K7 Dashcam",
    brand: "Innovv",
    price: 0,
    supplierUrl: "https://abikething.com/product/innovv-k7-motorcycle-dashcam-system-2/",
    subcategory: "Dash cameras",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/innovv-k7-motorcycle-dashcam-system-2/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/innovv-k7-motorcycle-dashcam-system-2/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "rider-tech-recording",
    description:
      "Dual-channel dashcam system aimed at ride capture, incident protection, and cleaner integrated installs.",
    image: demoAccessoryImages.usbHub.path,
    imageSourceLabel: demoAccessoryImages.usbHub.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/innovv-k7-motorcycle-dashcam-system-2/",
    fitmentConfidence: "Universal fit",
    featuredOrder: 20,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
      universal: true,
    },
  },
  {
    id: 7021,
    name: "B6 Rear Light",
    brand: "DENALI",
    price: 0,
    supplierUrl: "https://abikething.com/product/denali-b6-auxiliary-led-brake-light-with-high-level-bracket-r1300gsa/",
    subcategory: "Rear lights",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/denali-b6-auxiliary-led-brake-light-with-high-level-bracket-r1300gsa/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/denali-b6-auxiliary-led-brake-light-with-high-level-bracket-r1300gsa/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "safety-visibility",
    description:
      "Compact high-visibility rear brake light used to add conspicuity to a loaded touring bike.",
    image: demoAccessoryImages.ledLights.path,
    imageSourceLabel: demoAccessoryImages.ledLights.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/denali-b6-auxiliary-led-brake-light-with-high-level-bracket-r1300gsa/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 21,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
      universal: true,
    },
  },
  {
    id: 7022,
    name: "Split SoundBomb Horn",
    brand: "DENALI",
    price: 0,
    supplierUrl: "https://abikething.com/product/denali-split-soundbomb-120db-horn/",
    subcategory: "Horn systems",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/denali-split-soundbomb-120db-horn/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/denali-split-soundbomb-120db-horn/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "safety-visibility",
    description:
      "Split horn setup that keeps the install tidy while adding stronger road presence and warning capability.",
    image: demoAccessoryImages.usbHub.path,
    imageSourceLabel: demoAccessoryImages.usbHub.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/denali-split-soundbomb-120db-horn/",
    fitmentConfidence: "Universal fit",
    featuredOrder: 22,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7023,
    name: "Weiser Rear Dongles",
    brand: "Weiser",
    price: 0,
    supplierUrl:
      "https://abikething.com/product/weiser-extreme-evo-multifunction-led-run-brake-turn-rear-kit-r1250-gs-gsa-21-23/",
    subcategory: "Rear visibility",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/weiser-extreme-evo-multifunction-led-run-brake-turn-rear-kit-r1250-gs-gsa-21-23/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl:
      "https://abikething.com/product/weiser-extreme-evo-multifunction-led-run-brake-turn-rear-kit-r1250-gs-gsa-21-23/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "safety-visibility",
    description:
      "Weiser multifunction rear visibility upgrade used here as the rear dongle-style safety enhancement for the R1300GS/GSA platform.",
    image: demoAccessoryImages.ledLights.path,
    imageSourceLabel: demoAccessoryImages.ledLights.sourceLabel,
    sourceLabel: "ABikething search results",
    sourceUrl:
      "https://abikething.com/product/weiser-extreme-evo-multifunction-led-run-brake-turn-rear-kit-r1250-gs-gsa-21-23/",
    fitmentConfidence: "Exact fit",
    featuredOrder: 23,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7024,
    name: "Wireless Charger Mount",
    brand: "Peak Design",
    price: 0,
    supplierUrl: "https://abikething.com/product/peak-design-motorcycle-bar-mount-with-wireless-charging/",
    subcategory: "Phone mounts",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/peak-design-motorcycle-bar-mount-with-wireless-charging/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/peak-design-motorcycle-bar-mount-with-wireless-charging/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "connectivity-navigation",
    description:
      "Wireless charging phone mount that supports a cleaner touring cockpit without bulky navigation hardware.",
    image: demoAccessoryImages.gpsMount.path,
    imageSourceLabel: demoAccessoryImages.gpsMount.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/peak-design-motorcycle-bar-mount-with-wireless-charging/",
    fitmentConfidence: "Universal fit",
    featuredOrder: 24,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
      universal: true,
    },
  },
  {
    id: 7025,
    name: "Gilles Footpegs",
    brand: "Gilles",
    price: 0,
    supplierUrl: "https://abikething.com/?s=gilles&post_type=product",
    subcategory: "Foot controls",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/?s=gilles&post_type=product",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/?s=gilles&post_type=product",
    availabilityStatus: "available",
    commerceConfidence: "fallback",
    categoryId: "ergonomics",
    description:
      "Premium footpeg upgrade chosen to improve support and all-day comfort on the R1300GS/GSA platform.",
    image: demoAccessoryImages.risers.path,
    imageSourceLabel: demoAccessoryImages.risers.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/?s=gilles&post_type=product",
    fitmentConfidence: "Not confirmed",
    featuredOrder: 25,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
    },
  },
  {
    id: 7026,
    name: "GYS Flash Charger",
    brand: "GYS",
    price: 0,
    supplierUrl: "https://abikething.com/product/gysflash-1-12-uk/",
    subcategory: "Battery chargers",
    affiliateLinks: [
      {
        vendorName: "ABikething",
        url: "https://abikething.com/product/gysflash-1-12-uk/",
        label: "View at ABikething",
        priority: 1,
      },
    ],
    fallbackUrl: "https://abikething.com/product/gysflash-1-12-uk/",
    availabilityStatus: "available",
    commerceConfidence: "linked",
    categoryId: "power-support",
    description:
      "Battery support charger for a tech-loaded touring build that sits on chargers between rides.",
    image: demoAccessoryImages.usbHub.path,
    imageSourceLabel: demoAccessoryImages.usbHub.sourceLabel,
    sourceLabel: "ABikething product page",
    sourceUrl: "https://abikething.com/product/gysflash-1-12-uk/",
    fitmentConfidence: "Universal fit",
    featuredOrder: 26,
    compatibility: {
      bikeIds: bmwR1300GSFamily,
      universal: true,
    },
  },
];
